### PR TITLE
remove incomplete kserve-web-app (#147)

### PR DESCRIPTION
**Pull request by DnPlas**
This PR removes the stub charm for the kserve-web-app. This charm was never completed, and should not be included in main. kserve-web-app can be reintroduced into main when it is ready.

### CODE REVIEW

**Review by beliaev-maksim — APPROVED** [review]
finally :)

**Comment by beliaev-maksim** [comment]
@DnPlas please update publish job as well

**Comment by DnPlas** [comment]
@beliaev-maksim not sure why in my last commit the web-app directory was not removed completely, but anyway, I have updated the PR, do you mind approving again?

**Review by beliaev-maksim — APPROVED** [review]
lgtm if CI green

**Pull request merged**
